spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9093 # ??????? ????? ?????? ??????? Kafka
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      topic:
        kafkaMessageGroupId: "data-base"



    consumer:
      group-id: data-base # ?????? ????????????
      auto-offset-reset: earliest # ???????? ? ?????? ??????? ????????, ???? ???????? ?? ???????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      topic:
        topicList:

          - create-hotel
          - create-room

