server:
  port: 8088
spring:
  ssl.bundle.pem:
    client:
      truststore:
        certificate: classpath:cert/keystore.pem

app:
  ssl:
    client:
      p12:
        path: classpath:cert/keystore.p12
        password: "123456"

